<?php

namespace Zorbus\TrafficBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InboundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboundRepository extends EntityRepository
{
}
