<?php

namespace Zorbus\TrafficBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OutboundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutboundRepository extends EntityRepository
{
}
